/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.hamp_it.ftransfer;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.SocketException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tim
 */
public class MainFrame extends javax.swing.JFrame {

    private boolean connected = false;
    private ResourceBundle strings;
    private Socket clientSocket;
    private DataOutputStream dataOut;
    private DataInputStream dataIn;
    private final ResourceBundle message_bundle;
    private final ResourceBundle string_bundle;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        message_bundle = ResourceBundle.getBundle("messages", Locale.getDefault());
        string_bundle = ResourceBundle.getBundle("strings", Locale.getDefault());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        statusCaptionLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sendFileButton = new javax.swing.JButton();
        sendMessageButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        protocolLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FTransfer");

        addressField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressFieldKeyReleased(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("strings"); // NOI18N
        connectButton.setText(bundle.getString("caption_connect")); // NOI18N
        connectButton.setEnabled(false);
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        addressLabel.setText(bundle.getString("caption_address")); // NOI18N

        portLabel.setText(bundle.getString("caption_port")); // NOI18N

        portField.setText("50471");
        portField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                portFieldKeyReleased(evt);
            }
        });

        statusCaptionLabel.setText(bundle.getString("caption_status")); // NOI18N

        statusLabel.setText(bundle.getString("status_not_connected")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("caption_actions"))); // NOI18N

        sendFileButton.setText(bundle.getString("button_send_file")); // NOI18N
        sendFileButton.setEnabled(false);
        sendFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileButtonActionPerformed(evt);
            }
        });

        sendMessageButton.setText(bundle.getString("button_send_message")); // NOI18N
        sendMessageButton.setEnabled(false);
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageTextArea.setEnabled(false);
        messageTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                messageTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(messageTextArea);

        infoTextArea.setEditable(false);
        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        infoTextArea.setEnabled(false);
        jScrollPane2.setViewportView(infoTextArea);

        protocolLabel.setText(bundle.getString("caption_protocol")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendMessageButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(protocolLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageButton)
                    .addComponent(sendFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(protocolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addComponent(portLabel)
                            .addComponent(statusCaptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressField)
                            .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(portField))
                        .addGap(18, 18, 18)
                        .addComponent(connectButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusCaptionLabel)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if (connected) {
            // Disconnect
            try {
                dataOut.writeUTF("disconnect");
                clientSocket.close();
            } catch (IOException ex) {
                //
            }
            
            connectButton.setText(string_bundle.getString("caption_connect"));
            setConnectionEnabled(true);
            setActionsEditable(false);
            connected = false;
        } else {
            // Connect
            String address = addressField.getText().trim();
            Integer port = new Integer(portField.getText().trim());
            
            try {
                clientSocket = new Socket(address, port);
                dataOut = new DataOutputStream(clientSocket.getOutputStream());
                dataIn = new DataInputStream(clientSocket.getInputStream());
                boolean accept = dataIn.readBoolean();
                if (!accept) throw new IOException(message_bundle.getString("connection_error_or_refused"));
                statusLabel.setText(message_bundle.getString("connection_connected"));
                infoTextArea.append(message_bundle.getString("connection_connected_to") + " " + address + ":" + port.toString() + "\n");
                System.out.println(message_bundle.getString("connection_connected_to") + " " + address + ":" + port.toString());
            } catch (IOException ex) {
                statusLabel.setText(message_bundle.getString("connection_error"));
                return;
            }
            connectButton.setText(string_bundle.getString("caption_disconnect"));
            setConnectionEnabled(false);
            setActionsEditable(true);
            connected = true;
        }
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void addressFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressFieldKeyReleased
        if (addressField.getText().trim().length() > 0 && portField.getText().trim().length() > 0) {
            connectButton.setEnabled(true);
        } else {
            connectButton.setEnabled(false);
        }
    }//GEN-LAST:event_addressFieldKeyReleased

    private void portFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portFieldKeyReleased
        if (addressField.getText().trim().length() > 0 && portField.getText().trim().length() > 0) {
            connectButton.setEnabled(true);
        } else {
            connectButton.setEnabled(false);
        }
    }//GEN-LAST:event_portFieldKeyReleased

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        String message = messageTextArea.getText();
        try {
            dataOut.writeUTF("msg:" + message);
            boolean accept = dataIn.readBoolean();
            if (accept) {
                infoTextArea.append(message_bundle.getString("message_send_ok") + " " + message + "\n");
                messageTextArea.setText("");
                sendMessageButton.setEnabled(false);
            } else {
                throw new IOException(message_bundle.getString("message_unkown_answer"));
            }
        } catch (IOException ex) {
            infoTextArea.append(message_bundle.getString("message_send_error") + " " + message.substring(0, 5) + "...\n");
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_sendMessageButtonActionPerformed

    private void sendFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        int val = fileChooser.showDialog(null, string_bundle.getString("caption_send"));
        if (val != JFileChooser.APPROVE_OPTION) {
            System.out.println(message_bundle.getString("file_selection_aborted"));
            return;
        }
        File file = fileChooser.getSelectedFile();
        long fileSize = file.length();
        
        System.out.println(message_bundle.getString("file_selected") + ": " + file.getName() + " (" + fileSize + " " + message_bundle.getString("file_bytes") + ")");
        if (fileSize > 1000000000) {
            JOptionPane.showMessageDialog(null, message_bundle.getString("file_sive_overload"));
            return;
        }
        
        // TODO check file type
        
        try {
            dataOut.writeUTF("file:" + file.getName());
            dataOut.writeLong(fileSize);
            boolean accept = dataIn.readBoolean();
            if (accept) {
                System.out.println(message_bundle.getString("file_accepted"));
                infoTextArea.append(message_bundle.getString("file_file") + ": " + file.getName() + "\n");
                infoTextArea.append(message_bundle.getString("file_coding") + "\n");
                byte[] fileArray = writeFileToBytes(file);
                int length = fileArray.length;
                if (length <= 0) {
                    infoTextArea.append(message_bundle.getString("file_broken"));
                    return;
                }
                dataOut.writeInt(length);
                System.out.println(message_bundle.getString("file_sending"));
                infoTextArea.append(message_bundle.getString("file_sending") + " (" + length + " " + message_bundle.getString("file_bytes") + ")\n");
                dataOut.write(fileArray);
                System.out.println(message_bundle.getString("file_send_wait_for_answer"));
                Boolean success = dataIn.readBoolean();
                if (success) {
                    infoTextArea.append(message_bundle.getString("file_send_success") + "\n");
                    System.out.println(message_bundle.getString("file_send_success"));
                } else {
                    infoTextArea.append(message_bundle.getString("file_send_error") + "\n");
                    System.out.println(message_bundle.getString("file_send_error"));
                }
            } else {
                throw new IOException(message_bundle.getString("file_unkown_answer"));
            }
            
        } catch (SocketException ex) {
            infoTextArea.append(message_bundle.getString("file_send_error") + "\n");
            System.out.println(ex.toString());
            try {
                clientSocket.close();
            } catch (IOException es) {
                //
            }
            
        } catch (IOException ex) {
            infoTextArea.append(message_bundle.getString("file_send_error") + "\n");
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_sendFileButtonActionPerformed

    private void messageTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageTextAreaKeyReleased
        if (messageTextArea.getText().trim().length() <= 0) {
            sendMessageButton.setEnabled(false);
        } else {
            sendMessageButton.setEnabled(true);
        }
    }//GEN-LAST:event_messageTextAreaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField portField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel protocolLabel;
    private javax.swing.JButton sendFileButton;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JLabel statusCaptionLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Set the connection fields
     * @param value True for enable, false to disable
     */
    private void setConnectionEnabled(boolean value) {
        addressField.setEditable(value);
        portField.setEditable(value);
    }
    
    /**
     * Set the action fields
     * @param value True for enable, false to disable
     */
    private void setActionsEditable(boolean value) {
        sendFileButton.setEnabled(value);
        if (messageTextArea.getText().trim().length() > 0 && value) {
            sendMessageButton.setEnabled(true);
        } else {
            sendMessageButton.setEnabled(false);
        }
        messageTextArea.setEditable(value);
        messageTextArea.setEnabled(value);
        infoTextArea.setEnabled(value);
    }
    
    /**
     * Converts a file to byte array to send over the network
     * @param file File to convert
     * @return Byte array of file
     */
    private static byte[] writeFileToBytes(File file) throws IOException {
        byte[] fileArray = new byte[(int) file.length()];
        
        FileInputStream fis = new FileInputStream(file);
        fis.read(fileArray);
        fis.close();
        
        return fileArray;
    }
}
